server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/customer/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: "admin"

        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: "user"

        - id: dashboard-service
          uri: http://localhost:8084
          predicates:
            - Path=/dashboard/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: "admin,user"

       
